### PR TITLE
julia 1 compatibility

### PR DESCRIPTION
**Pull request by stevengj**
`runtests.jl` passes, but I haven't done any other checks.

(Also closes #6.)

### CODE REVIEW

**Comment by stevengj** [comment]
@simonster, can ownership of this package be transferred to some other person/organization so that it can be maintained?

**Comment by stevengj** [comment]
ping

**Comment by simonster** [comment]
Sorry for missing this. Any thoughts where it should go? Maybe JuliaStats?

**Comment by stevengj** [comment]
JuliaStats seems like a good choice, and it looks like you are already a member of that org.

**Pull request merged**
